[package]
name = "lyra-remote"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lyra-core = { path = "../lyra-core" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread", "time"] }
tracing.workspace = true

sha2 = "0.10"
subtle = "2.6"
rand = "0.8"
snow = "0.10.0"
spake2 = "0.4.0"

[lints]
workspace = true
